# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/akoeninger/.local/lib/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/akoeninger/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akoeninger/pire

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akoeninger/pire/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/akoeninger/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/akoeninger/.local/lib/python2.7/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akoeninger/pire/build/CMakeFiles /home/akoeninger/pire/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akoeninger/pire/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pire

# Build rule for target.
pire: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pire
.PHONY : pire

# fast build rule for target.
pire/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/build
.PHONY : pire/fast

#=============================================================================
# Target rules for targets named fuzz

# Build rule for target.
fuzz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fuzz
.PHONY : fuzz

# fast build rule for target.
fuzz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/build
.PHONY : fuzz/fast

# target to build an object file
fuzz.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.o
.PHONY : fuzz.o

# target to preprocess a source file
fuzz.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.i
.PHONY : fuzz.i

# target to generate assembly for a file
fuzz.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.s
.PHONY : fuzz.s

# target to build an object file
pire/approx_matching.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/approx_matching.o
.PHONY : pire/approx_matching.o

# target to preprocess a source file
pire/approx_matching.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/approx_matching.i
.PHONY : pire/approx_matching.i

# target to generate assembly for a file
pire/approx_matching.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/approx_matching.s
.PHONY : pire/approx_matching.s

# target to build an object file
pire/classes.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/classes.o
.PHONY : pire/classes.o

# target to preprocess a source file
pire/classes.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/classes.i
.PHONY : pire/classes.i

# target to generate assembly for a file
pire/classes.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/classes.s
.PHONY : pire/classes.s

# target to build an object file
pire/easy.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/easy.o
.PHONY : pire/easy.o

# target to preprocess a source file
pire/easy.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/easy.i
.PHONY : pire/easy.i

# target to generate assembly for a file
pire/easy.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/easy.s
.PHONY : pire/easy.s

# target to build an object file
pire/encoding.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/encoding.o
.PHONY : pire/encoding.o

# target to preprocess a source file
pire/encoding.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/encoding.i
.PHONY : pire/encoding.i

# target to generate assembly for a file
pire/encoding.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/encoding.s
.PHONY : pire/encoding.s

# target to build an object file
pire/extra/capture.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/capture.o
.PHONY : pire/extra/capture.o

# target to preprocess a source file
pire/extra/capture.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/capture.i
.PHONY : pire/extra/capture.i

# target to generate assembly for a file
pire/extra/capture.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/capture.s
.PHONY : pire/extra/capture.s

# target to build an object file
pire/extra/count.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/count.o
.PHONY : pire/extra/count.o

# target to preprocess a source file
pire/extra/count.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/count.i
.PHONY : pire/extra/count.i

# target to generate assembly for a file
pire/extra/count.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/count.s
.PHONY : pire/extra/count.s

# target to build an object file
pire/extra/glyphs.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/glyphs.o
.PHONY : pire/extra/glyphs.o

# target to preprocess a source file
pire/extra/glyphs.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/glyphs.i
.PHONY : pire/extra/glyphs.i

# target to generate assembly for a file
pire/extra/glyphs.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/extra/glyphs.s
.PHONY : pire/extra/glyphs.s

# target to build an object file
pire/fsm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/fsm.o
.PHONY : pire/fsm.o

# target to preprocess a source file
pire/fsm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/fsm.i
.PHONY : pire/fsm.i

# target to generate assembly for a file
pire/fsm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/fsm.s
.PHONY : pire/fsm.s

# target to build an object file
pire/half_final_fsm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/half_final_fsm.o
.PHONY : pire/half_final_fsm.o

# target to preprocess a source file
pire/half_final_fsm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/half_final_fsm.i
.PHONY : pire/half_final_fsm.i

# target to generate assembly for a file
pire/half_final_fsm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/half_final_fsm.s
.PHONY : pire/half_final_fsm.s

# target to build an object file
pire/re_lexer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_lexer.o
.PHONY : pire/re_lexer.o

# target to preprocess a source file
pire/re_lexer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_lexer.i
.PHONY : pire/re_lexer.i

# target to generate assembly for a file
pire/re_lexer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_lexer.s
.PHONY : pire/re_lexer.s

# target to build an object file
pire/re_parser.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_parser.o
.PHONY : pire/re_parser.o

# target to preprocess a source file
pire/re_parser.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_parser.i
.PHONY : pire/re_parser.i

# target to generate assembly for a file
pire/re_parser.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/re_parser.s
.PHONY : pire/re_parser.s

# target to build an object file
pire/read_unicode.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/read_unicode.o
.PHONY : pire/read_unicode.o

# target to preprocess a source file
pire/read_unicode.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/read_unicode.i
.PHONY : pire/read_unicode.i

# target to generate assembly for a file
pire/read_unicode.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/read_unicode.s
.PHONY : pire/read_unicode.s

# target to build an object file
pire/scanner_io.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanner_io.o
.PHONY : pire/scanner_io.o

# target to preprocess a source file
pire/scanner_io.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanner_io.i
.PHONY : pire/scanner_io.i

# target to generate assembly for a file
pire/scanner_io.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanner_io.s
.PHONY : pire/scanner_io.s

# target to build an object file
pire/scanners/null.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanners/null.o
.PHONY : pire/scanners/null.o

# target to preprocess a source file
pire/scanners/null.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanners/null.i
.PHONY : pire/scanners/null.i

# target to generate assembly for a file
pire/scanners/null.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/scanners/null.s
.PHONY : pire/scanners/null.s

# target to build an object file
pire/stub/utf8.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/stub/utf8.o
.PHONY : pire/stub/utf8.o

# target to preprocess a source file
pire/stub/utf8.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/stub/utf8.i
.PHONY : pire/stub/utf8.i

# target to generate assembly for a file
pire/stub/utf8.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pire.dir/build.make CMakeFiles/pire.dir/pire/stub/utf8.s
.PHONY : pire/stub/utf8.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fuzz"
	@echo "... pire"
	@echo "... fuzz.o"
	@echo "... fuzz.i"
	@echo "... fuzz.s"
	@echo "... pire/approx_matching.o"
	@echo "... pire/approx_matching.i"
	@echo "... pire/approx_matching.s"
	@echo "... pire/classes.o"
	@echo "... pire/classes.i"
	@echo "... pire/classes.s"
	@echo "... pire/easy.o"
	@echo "... pire/easy.i"
	@echo "... pire/easy.s"
	@echo "... pire/encoding.o"
	@echo "... pire/encoding.i"
	@echo "... pire/encoding.s"
	@echo "... pire/extra/capture.o"
	@echo "... pire/extra/capture.i"
	@echo "... pire/extra/capture.s"
	@echo "... pire/extra/count.o"
	@echo "... pire/extra/count.i"
	@echo "... pire/extra/count.s"
	@echo "... pire/extra/glyphs.o"
	@echo "... pire/extra/glyphs.i"
	@echo "... pire/extra/glyphs.s"
	@echo "... pire/fsm.o"
	@echo "... pire/fsm.i"
	@echo "... pire/fsm.s"
	@echo "... pire/half_final_fsm.o"
	@echo "... pire/half_final_fsm.i"
	@echo "... pire/half_final_fsm.s"
	@echo "... pire/re_lexer.o"
	@echo "... pire/re_lexer.i"
	@echo "... pire/re_lexer.s"
	@echo "... pire/re_parser.o"
	@echo "... pire/re_parser.i"
	@echo "... pire/re_parser.s"
	@echo "... pire/read_unicode.o"
	@echo "... pire/read_unicode.i"
	@echo "... pire/read_unicode.s"
	@echo "... pire/scanner_io.o"
	@echo "... pire/scanner_io.i"
	@echo "... pire/scanner_io.s"
	@echo "... pire/scanners/null.o"
	@echo "... pire/scanners/null.i"
	@echo "... pire/scanners/null.s"
	@echo "... pire/stub/utf8.o"
	@echo "... pire/stub/utf8.i"
	@echo "... pire/stub/utf8.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

